using UnityEngine;

// Hand-maintained, NOT generated by `make sync-unity` — holds Unity-only adaptations on top of
// the generated CPU.cs/VerilatorClient.cs/FPGAClient.cs so those files never need Unity-specific
// edits. Add new Unity-only needs here instead of hand-patching the generated files.
public static class CPUUnityExtensions
{
    // Create an ICPU from already-assembled level JSON instructions (InstructionData[] is a
    // Unity-only type, see Assets/Scripts/LevelData.cs), bypassing file I/O.
    public static ICPU Create(InstructionData[] instructions, CPUFactory.ImplementationType type = CPUFactory.ImplementationType.Verilator)
    {
        string[] hexInstructions = new string[instructions.Length];
        for (int i = 0; i < instructions.Length; i++)
        {
            if (string.IsNullOrEmpty(instructions[i].hex))
            {
                Debug.LogError($"CPU: instruction '{instructions[i].label}' is missing a 'hex' field");
                hexInstructions[i] = "00000000";
                continue;
            }
            hexInstructions[i] = instructions[i].hex;
        }
        return CPUFactory.Create(hexInstructions, type);
    }
}
